// AUTO-GENERATED by scripts/sync-lab.mjs — do not edit manually.
// Run: npm run sync-lab
// Note: featured field added manually after generation.

export interface LabProject {
  slug: string
  title: string
  description: string
  tags: string[]
  status: 'prototype' | 'finished' | 'active'
  demoUrl: string
  featured?: boolean
}

export const labProjects: LabProject[] = [
  {
    "slug": "pixel-art",
    "title": "Pixel Art Editor",
    "description": "A feature-rich pixel art editor with nature-inspired color palettes, symmetry drawing modes, spray brush, adjustable canvas sizes, and rotating Bob Ross quotes. Paint happy little trees!",
    "tags": [
      "HTML",
      "CSS",
      "JavaScript",
      "Canvas API"
    ],
    "status": "finished",
    "demoUrl": "/demos/pixel-art/index.html",
    "featured": true
  },
  {
    "slug": "simon-says",
    "title": "Simon Says Game",
    "description": "A classic memory game where players must repeat an increasingly complex sequence of colors. Test your memory and concentration skills!",
    "tags": [
      "HTML",
      "CSS",
      "JavaScript"
    ],
    "status": "finished",
    "demoUrl": "/demos/simon-says/index.html"
  },
  {
    "slug": "tic-tac-toe",
    "title": "Tic Tac Toe — Neural Grid",
    "description": "A cyberpunk-themed Tic Tac Toe game with three AI difficulty levels — from casual random moves to an unbeatable minimax algorithm with alpha-beta pruning.",
    "tags": [
      "HTML",
      "CSS",
      "JavaScript"
    ],
    "status": "finished",
    "demoUrl": "/demos/tic-tac-toe/index.html",
    "featured": true
  }
]
