// AUTO-GENERATED by scripts/sync-lab.mjs — do not edit manually.
// Run: npm run sync-lab

export interface LabProject {
  slug: string
  title: string
  description: string
  techNotes?: string
  tags: string[]
  status: 'live' | 'prototype' | 'experiment' | 'coming soon'
  demoUrl: string
  featured?: boolean
  hidden?: boolean
}

export const labProjects: LabProject[] = [
  {
    "slug": "flowerquest",
    "title": "Monnie's Flower Quest",
    "description": "A polished mobile-first garden adventure where Monnie collects flowers, dodges beetles, bees & wasps, collects power blooms, and unlocks the garden gate across ten handcrafted levels.",
    "techNotes": "Phaser gameplay embedded through the lab shell, with standalone game deployed on Vercel.",
    "featured": true,
    "hidden": true,
    "tags": [
      "Phaser",
      "React",
      "TypeScript",
      "Vite"
    ],
    "status": "live",
    "demoUrl": "/lab/flowerquest/"
  },
  {
    "slug": "south-florida-fighter",
    "title": "South Florida Fighter",
    "description": "A vibrant 2D arcade fighter set on the boardwalks and beaches of South Florida, featuring special cancels, locked 60 FPS combat, and dynamic audio DSP.",
    "techNotes": "Custom 2D arcade engine with frame-accurate cancel windows, deployed on Vercel.",
    "featured": true,
    "tags": [
      "Arcade",
      "Canvas",
      "TypeScript",
      "Vite"
    ],
    "status": "live",
    "demoUrl": "/lab/south-florida-fighter/"
  },
  {
    "slug": "simon-says",
    "title": "Simon Says Game",
    "description": "A classic memory game where players must repeat an increasingly complex sequence of colors. Test your memory and concentration skills!",
    "techNotes": "State machine flow + tuned timing for difficulty ramp.",
    "featured": true,
    "tags": [
      "HTML",
      "CSS",
      "JavaScript"
    ],
    "status": "live",
    "demoUrl": "/lab/simon-says/"
  },
  {
    "slug": "tic-tac-toe",
    "title": "Tic Tac Toe — Neural Grid",
    "description": "A cyberpunk-themed Tic Tac Toe game with three AI difficulty levels — from casual random moves to an unbeatable minimax algorithm with alpha-beta pruning.",
    "techNotes": "Minimax with score-depth weighting for cleaner AI decisions.",
    "featured": true,
    "tags": [
      "HTML",
      "CSS",
      "JavaScript"
    ],
    "status": "live",
    "demoUrl": "/lab/tic-tac-toe/"
  }
]
