/**
 * Lab Projects — Central data source
 *
 * These are smaller experiments and prototypes.
 * Used by: Lab page
 *
 * Note: The previous version was auto-generated by scripts/sync-lab.mjs.
 * You can still run `npm run sync-lab` to regenerate, or edit manually.
 */

export interface LabProject {
  slug: string
  title: string
  description: string
  tags: string[]
  status: 'prototype' | 'finished' | 'active'
  demoUrl: string
  featured?: boolean
}

export const labProjects: LabProject[] = [
  {
    slug: 'pixel-art',
    title: 'Pixel Art Editor',
    description:
      'A feature-rich pixel art editor with nature-inspired color palettes, symmetry drawing modes, spray brush, adjustable canvas sizes, and rotating Bob Ross quotes.',
    tags: ['JavaScript', 'CSS', 'Game', 'Canvas API'],
    status: 'finished',
    demoUrl: '/demos/pixel-art/index.html',
    featured: true,
  },
  {
    slug: 'simon-says',
    title: 'Simon Says Game',
    description:
      'A classic memory game where players must repeat an increasingly complex sequence of colors. Test your memory and concentration skills!',
    tags: ['JavaScript', 'Game', 'CSS'],
    status: 'finished',
    demoUrl: '/demos/simon-says/index.html',
  },
  {
    slug: 'tic-tac-toe',
    title: 'Tic Tac Toe — Neural Grid',
    description:
      'A cyberpunk-themed Tic Tac Toe game with three AI difficulty levels — from casual random moves to an unbeatable minimax algorithm.',
    tags: ['JavaScript', 'Game', 'AI / Minimax'],
    status: 'finished',
    demoUrl: '/demos/tic-tac-toe/index.html',
    featured: true,
  },
  {
    slug: 'css-hover-gallery',
    title: 'CSS Hover Gallery',
    description:
      'A pure CSS image gallery with creative hover transitions and blend modes. No JavaScript required.',
    tags: ['CSS', 'UI Experiment', 'Animation'],
    status: 'prototype',
    demoUrl: '#',
  },
  {
    slug: 'gradient-generator',
    title: 'Gradient Generator',
    description:
      'A tool for generating and previewing CSS gradients with real-time controls. Copy the code and use it anywhere.',
    tags: ['JavaScript', 'UI Experiment', 'CSS'],
    status: 'active',
    demoUrl: '#',
  },
]
