/**
 * sync-lab.mjs
 * Scans public/demos/ and generates src/lib/lab-projects.ts
 * Run: npm run sync-lab
 */

import { readdir, readFile, writeFile, access } from 'fs/promises'
import { join, resolve } from 'path'
import { fileURLToPath } from 'url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const ROOT = resolve(__dirname, '..')
const LAB_DIR = join(ROOT, 'public', 'demos')
const OUT = join(ROOT, 'src', 'lib', 'lab-projects.ts')

function slugToTitle(slug) {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

async function fileExists(p) {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}

function mapStatus(raw) {
  if (!raw) return 'prototype'
  if (raw === 'completed' || raw === 'finished' || raw === 'live') return 'live'
  if (raw === 'active' || raw === 'experiment') return 'experiment'
  if (raw === 'coming soon') return 'coming soon'
  return 'prototype'
}

const HOSTED_PROJECTS = [
  {
    slug: 'flowerquest',
    title: "Monnie's Flower Quest",
    description:
      'A polished mobile-first garden adventure where Monnie collects flowers, dodges beetles, bees & wasps, collects power blooms, and unlocks the garden gate across ten handcrafted levels.',
    techNotes:
      'Phaser gameplay embedded through the lab shell, with standalone game deployed on Vercel.',
    featured: true,
    hidden: true,
    tags: ['Phaser', 'React', 'TypeScript', 'Vite'],
    status: 'live',
    demoUrl: '/lab/flowerquest/',
  },
  {
    slug: 'south-florida-fighter',
    title: 'South Florida Fighter',
    description:
      'A vibrant 2D arcade fighter set on the boardwalks and beaches of South Florida, featuring special cancels, locked 60 FPS combat, and dynamic audio DSP.',
    techNotes:
      'Custom 2D arcade engine with frame-accurate cancel windows, deployed on Vercel.',
    featured: true,
    tags: ['Arcade', 'Canvas', 'TypeScript', 'Vite'],
    status: 'live',
    demoUrl: '/lab/south-florida-fighter/',
  },
]

async function main() {
  const entries = await readdir(LAB_DIR, { withFileTypes: true })
  const folders = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()

  const projects = [...HOSTED_PROJECTS]

  for (const slug of folders) {
    const dir = join(LAB_DIR, slug)

    // Must have an index.html to be a valid lab project
    if (!(await fileExists(join(dir, 'index.html')))) continue

    let meta = {}
    const jsonPath = join(dir, 'project.json')
    if (await fileExists(jsonPath)) {
      try {
        const raw = await readFile(jsonPath, 'utf8')
        meta = JSON.parse(raw)
      } catch {
        console.warn(`⚠ Could not parse ${jsonPath} — using defaults`)
      }
    }

    projects.push({
      slug,
      title: meta.title ?? slugToTitle(slug),
      description:
        meta.description ??
        `A lab experiment exploring ${slugToTitle(slug).toLowerCase()}.`,
      techNotes: meta.techNotes,
      featured: meta.featured,
      tags: Array.isArray(meta.technologies)
        ? meta.technologies
        : ['HTML', 'CSS', 'JavaScript'],
      status: mapStatus(meta.status),
      demoUrl: `/lab/${slug}/`,
    })
  }

  const code = `// AUTO-GENERATED by scripts/sync-lab.mjs — do not edit manually.
// Run: npm run sync-lab

export interface LabProject {
  slug: string
  title: string
  description: string
  techNotes?: string
  tags: string[]
  status: 'live' | 'prototype' | 'experiment' | 'coming soon'
  demoUrl: string
  featured?: boolean
  hidden?: boolean
}

export const labProjects: LabProject[] = ${JSON.stringify(projects, null, 2)}
`

  await writeFile(OUT, code, 'utf8')
  console.log(
    `✓ Synced ${projects.length} lab project${projects.length !== 1 ? 's' : ''} → src/lib/lab-projects.ts`
  )
  projects.forEach((p) => console.log(`  • ${p.slug} (${p.status})`))
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
