/**
 * sync-lab.mjs
 * Scans public/demos/ and generates src/lib/lab-projects.ts
 * Run: npm run sync-lab
 */

import { readdir, readFile, writeFile, access } from 'fs/promises'
import { join, resolve } from 'path'
import { fileURLToPath } from 'url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const ROOT = resolve(__dirname, '..')
const LAB_DIR = join(ROOT, 'public', 'demos')
const OUT = join(ROOT, 'src', 'lib', 'lab-projects.ts')

function slugToTitle(slug) {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

async function fileExists(p) {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}

function mapStatus(raw) {
  if (!raw) return 'prototype'
  if (raw === 'completed' || raw === 'finished') return 'finished'
  if (raw === 'active') return 'active'
  return 'prototype'
}

async function main() {
  const entries = await readdir(LAB_DIR, { withFileTypes: true })
  const folders = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()

  const projects = []

  for (const slug of folders) {
    const dir = join(LAB_DIR, slug)

    // Must have an index.html to be a valid lab project
    if (!(await fileExists(join(dir, 'index.html')))) continue

    let meta = {}
    const jsonPath = join(dir, 'project.json')
    if (await fileExists(jsonPath)) {
      try {
        const raw = await readFile(jsonPath, 'utf8')
        meta = JSON.parse(raw)
      } catch {
        console.warn(`⚠ Could not parse ${jsonPath} — using defaults`)
      }
    }

    projects.push({
      slug,
      title: meta.title ?? slugToTitle(slug),
      description:
        meta.description ??
        `A lab experiment exploring ${slugToTitle(slug).toLowerCase()}.`,
      tags: Array.isArray(meta.technologies)
        ? meta.technologies
        : ['HTML', 'CSS', 'JavaScript'],
      status: mapStatus(meta.status),
      demoUrl: `/demos/${slug}/index.html`,
    })
  }

  const code = `// AUTO-GENERATED by scripts/sync-lab.mjs — do not edit manually.
// Run: npm run sync-lab

export interface LabProject {
  slug: string
  title: string
  description: string
  tags: string[]
  status: 'prototype' | 'finished' | 'active'
  demoUrl: string
}

export const labProjects: LabProject[] = ${JSON.stringify(projects, null, 2)}
`

  await writeFile(OUT, code, 'utf8')
  console.log(
    `✓ Synced ${projects.length} lab project${projects.length !== 1 ? 's' : ''} → src/lib/lab-projects.ts`
  )
  projects.forEach((p) => console.log(`  • ${p.slug} (${p.status})`))
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
